name: control_reunion
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_local_notifications: 
  get: 4.6.5
  get_storage: 2.0.3
  syncfusion_flutter_calendar: 
  numberpicker: 2.1.1
  string_to_hex: 0.2.2
  syncfusion_localizations: 
  firebase_messaging: ^13.0.2
  firebase_core: ^1.22.0
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

